## Creating student info

In [1]:
import pandas as pd
import numpy as np
student_info = pd.DataFrame({
    'studentid':[101,102,103,104,105,106,107,108],
'Name':['Aayush','Ali','Binisha','Bijeta','Chandani','Chandra','Heena','Raju'],
'Age':[19,18,19,19,18,17,18,18],
'Math':[85,92,70,77,80,23,90,50],
'Science':[78,20,75,80,77,56,65,80],
'English':[85,80,81,90,91,90,89,76],
'Computer':[88,89,55,80,34,56,76,60],
'Social':[72,76,80,91,77,80,98,44],
'Attendance':[95,98,90,90,55,95,90,60]
})

##### converted to csv file

In [2]:
student_info.to_csv('student_info.csv')

In [3]:
student_info

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance
0,101,Aayush,19,85,78,85,88,72,95
1,102,Ali,18,92,20,80,89,76,98
2,103,Binisha,19,70,75,81,55,80,90
3,104,Bijeta,19,77,80,90,80,91,90
4,105,Chandani,18,80,77,91,34,77,55
5,106,Chandra,17,23,56,90,56,80,95
6,107,Heena,18,90,65,89,76,98,90
7,108,Raju,18,50,80,76,60,44,60

#### Adding new column Gender

In [4]:
student_info['Gender'] = ['Male','Male','Female','Female','Female','Male','Female','Male']

In [5]:
student_info

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Gender
0,101,Aayush,19,85,78,85,88,72,95,Male
1,102,Ali,18,92,20,80,89,76,98,Male
2,103,Binisha,19,70,75,81,55,80,90,Female
3,104,Bijeta,19,77,80,90,80,91,90,Female
4,105,Chandani,18,80,77,91,34,77,55,Female
5,106,Chandra,17,23,56,90,56,80,95,Male
6,107,Heena,18,90,65,89,76,98,90,Female
7,108,Raju,18,50,80,76,60,44,60,Male

#### Computing and adding the Total to the student_info dataframe

In [6]:
# Computing and adding the Total to the student_info dataframe
student_info['Total']= student_info['Math']+student_info['Science']+student_info['English']+student_info['Computer']+student_info['Social']

In [7]:
student_info

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Gender,Total
0,101,Aayush,19,85,78,85,88,72,95,Male,408
1,102,Ali,18,92,20,80,89,76,98,Male,357
2,103,Binisha,19,70,75,81,55,80,90,Female,361
3,104,Bijeta,19,77,80,90,80,91,90,Female,418
4,105,Chandani,18,80,77,91,34,77,55,Female,359
5,106,Chandra,17,23,56,90,56,80,95,Male,305
6,107,Heena,18,90,65,89,76,98,90,Female,418
7,108,Raju,18,50,80,76,60,44,60,Male,310

#### Computing Total Percentage obtained by each student

In [8]:
no_of_subjects=5
student_info['Percentage']=student_info['Total']/no_of_subjects

In [9]:
student_info

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Gender,Total,Percentage
0,101,Aayush,19,85,78,85,88,72,95,Male,408,81.6
1,102,Ali,18,92,20,80,89,76,98,Male,357,71.4
2,103,Binisha,19,70,75,81,55,80,90,Female,361,72.2
3,104,Bijeta,19,77,80,90,80,91,90,Female,418,83.6
4,105,Chandani,18,80,77,91,34,77,55,Female,359,71.8
5,106,Chandra,17,23,56,90,56,80,95,Male,305,61.0
6,107,Heena,18,90,65,89,76,98,90,Female,418,83.6
7,108,Raju,18,50,80,76,60,44,60,Male,310,62.0

## Calculate the Gpa according to Percentage and display the Gpa

In [10]:
print(student_info.columns)

Index(['studentid', 'Name', 'Age', 'Math', 'Science', 'English', 'Computer',
       'Social', 'Attendance', 'Gender', 'Total', 'Percentage'],
      dtype='object')

In [11]:
student_info['Grade'] =student_info.loc[(student_info['Percentage'] >= 90), 'Grade'] = 'A+'
student_info.loc[(student_info['Percentage'] >= 80) & (student_info['Percentage'] < 90), 'Grade'] = 'A'
student_info.loc[(student_info['Percentage'] >= 70) & (student_info['Percentage'] < 80), 'Grade'] = 'B'
student_info.loc[(student_info['Percentage'] >= 60) & (student_info['Percentage'] < 70), 'Grade'] = 'C'
student_info.loc[(student_info['Percentage'] < 60), 'Grade'] = 'F'

In [12]:
student_info

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Gender,Total,Percentage,Grade
0,101,Aayush,19,85,78,85,88,72,95,Male,408,81.6,A
1,102,Ali,18,92,20,80,89,76,98,Male,357,71.4,B
2,103,Binisha,19,70,75,81,55,80,90,Female,361,72.2,B
3,104,Bijeta,19,77,80,90,80,91,90,Female,418,83.6,A
4,105,Chandani,18,80,77,91,34,77,55,Female,359,71.8,B
5,106,Chandra,17,23,56,90,56,80,95,Male,305,61.0,C
6,107,Heena,18,90,65,89,76,98,90,Female,418,83.6,A
7,108,Raju,18,50,80,76,60,44,60,Male,310,62.0,C

### Creating a condition where student who got below 40 in any subject fails and who got above or equal to 40 will pass

In [13]:
student_info['Result']=student_info.loc[(student_info['Math'] >= 40) & (student_info['Science'] >= 40) & (student_info['English'] >= 40) & (student_info['Computer'] >= 40) & (student_info['Social'] >= 40) , 'Result']='PASS'
student_info.loc[(student_info['Math'] < 40) | (student_info['Science'] < 40) | (student_info['English'] < 40) | (student_info['Computer'] < 40) | (student_info['Social'] < 40) , 'Result']='FAIL'

In [14]:
student_info

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Gender,Total,Percentage,Grade,Result
0,101,Aayush,19,85,78,85,88,72,95,Male,408,81.6,A,PASS
1,102,Ali,18,92,20,80,89,76,98,Male,357,71.4,B,FAIL
2,103,Binisha,19,70,75,81,55,80,90,Female,361,72.2,B,PASS
3,104,Bijeta,19,77,80,90,80,91,90,Female,418,83.6,A,PASS
4,105,Chandani,18,80,77,91,34,77,55,Female,359,71.8,B,FAIL
5,106,Chandra,17,23,56,90,56,80,95,Male,305,61.0,C,FAIL
6,107,Heena,18,90,65,89,76,98,90,Female,418,83.6,A,PASS
7,108,Raju,18,50,80,76,60,44,60,Male,310,62.0,C,PASS

In [15]:
student_info.groupby('Result')['Result'].count()

Result
FAIL    3
PASS    5
Name: Result, dtype: int64

## Finding the maximum percentage obtained with all details

In [16]:
# Here we can see the rank according to the percentage (i.e. topper who score highest to lowest)
student_info.groupby('Percentage').max().sort_values('Percentage',ascending=False)

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Gender,Total,Grade,Result
Percentage,,,,,,,,,,,,,
83.6,107,Heena,19,90,80,90,80,98,90,Female,418,A,PASS
81.6,101,Aayush,19,85,78,85,88,72,95,Male,408,A,PASS
72.2,103,Binisha,19,70,75,81,55,80,90,Female,361,B,PASS
71.8,105,Chandani,18,80,77,91,34,77,55,Female,359,B,FAIL
71.4,102,Ali,18,92,20,80,89,76,98,Male,357,B,FAIL
62.0,108,Raju,18,50,80,76,60,44,60,Male,310,C,PASS
61.0,106,Chandra,17,23,56,90,56,80,95,Male,305,C,FAIL

In [17]:
# Finding the highest marks obtained in each subject
print('Highest marks scored in Maths is ',student_info["Math"].max())
print('Highest marks scored in Science is ',student_info["Science"].max())
print('Highest marks scored in English is ',student_info["English"].max())
print('Highest marks scored in Computer is ',student_info["Computer"].max())
print('Highest marks scored in Social is ',student_info["Social"].max())

Highest marks scored in Maths is  92
Highest marks scored in Science is  80
Highest marks scored in English is  91
Highest marks scored in Computer is  89
Highest marks scored in Social is  98

## Finding the average marks obtained in each subject

In [18]:

print('Average marks scored in Maths is ',student_info["Math"].mean())
print('Average marks scored in Science is ',student_info["Science"].mean())
print('Average marks scored in English is ',student_info["English"].mean())
print('Average marks scored in Computer is ',student_info["Computer"].mean())
print('Average marks scored in Social is ',student_info["Social"].mean())

Average marks scored in Maths is  70.875
Average marks scored in Science is  66.375
Average marks scored in English is  85.25
Average marks scored in Computer is  67.25
Average marks scored in Social is  77.25

## Students who scored over or equal to 80%

In [19]:
high_score = student_info.loc[student_info['Percentage']>=80]
high_score

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Gender,Total,Percentage,Grade,Result
0,101,Aayush,19,85,78,85,88,72,95,Male,408,81.6,A,PASS
3,104,Bijeta,19,77,80,90,80,91,90,Female,418,83.6,A,PASS
6,107,Heena,18,90,65,89,76,98,90,Female,418,83.6,A,PASS

## Students who have attendance below 75%

In [20]:
low_attendance = student_info.loc[student_info['Attendance']<75]
low_attendance

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Gender,Total,Percentage,Grade,Result
4,105,Chandani,18,80,77,91,34,77,55,Female,359,71.8,B,FAIL
7,108,Raju,18,50,80,76,60,44,60,Male,310,62.0,C,PASS

### Subject with highest average (i.e. Easy subject)

In [21]:
subjects=student_info.iloc[:,3:8]
subject_mean=subjects.mean()
subject_mean

Math        70.875
Science     66.375
English     85.250
Computer    67.250
Social      77.250
dtype: float64

In [22]:
print(f'Subject with highest average is ',subject_mean.idxmax(),':',subject_mean.max())

Subject with highest average is  English : 85.25

### Subject with lowest average (i.e. Hardest subject)¶

In [23]:
subject_low_mean = subject_mean.min()
print(f'Subject with lowest average is ',subject_mean.idxmin(),':',subject_mean.min())

Subject with lowest average is  Science : 66.375

In [24]:
student_info.groupby('Gender').count()

,studentid,Name,Age,Math,Science,English,Computer,Social,Attendance,Total,Percentage,Grade,Result
Gender,,,,,,,,,,,,,
Female,4,4,4,4,4,4,4,4,4,4,4,4,4
Male,4,4,4,4,4,4,4,4,4,4,4,4,4

In [1]:
pwd

'C:\\Users\\Dell\\studentresultsystem'

In [ ]:
!git init
!git add README.md
!git add .
!git commit -m "Student resu"
!git branch -M main
!git remote add origin https://github.com/binita21/numpy_pandas_projects.git
!git push -u origin main